image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - choco install gitversion.portable -y

build_script:
  - qmake.exe e2designer.pro -spec win32-msvc 
  - jom.exe

after_build:
  - mkdir deploy
  - copy release\e2designer.exe deploy\e2designer.exe
  - windeployqt --release deploy/e2designer.exe
  - ps: |
      $version = git describe
      Update-AppveyorBuild -Version ${version}
      7z a e2designer_${version}_win.zip .\deploy\*

artifacts:
  - path: '*.zip'

deploy:
- provider: BinTray
  username: technic
  api_key:
    secure: jy1FUyYxHh37QsyYOVcrEHNNZLU/T9FFoWwiO4TVcUSfQ4zGu66G/dwxbwSqutfr
  subject: technic
  repo: e2designer
  package: e2designer
