image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
  - qmake.exe e2designer.pro -spec win32-msvc 
  - jom.exe

after_build:
  - mkdir deploy
  - copy release\e2designer.exe deploy\e2designer.exe
  - windeployqt --release deploy/e2designer.exe
  - 7z a EzGraver_win_%arch%.zip .\deploy\*

artifacts:
  - path: '*.7z'

deploy:
- provider: BinTray
  username: technic93
  api_key:
    secure: AABBCC+DDD==
  subject: technic93
  repo: e2designer
  package: e2designer
