image: Visual Studio 2017

install:
  - set QTDIR=C:\Qt\5.11.1\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin
  # is it required?
  # - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
  - qmake.exe e2designer.pro -spec win32-msvc 
  - jom.exe
