image: registry.gitlab.com/technic93/e2designer:latest

# To run tests with local image use
# gitlab-runner exec docker --docker-pull-policy="if-not-present" <command>

variables:
    UBUNTU_IMAGE: registry.gitlab.com/technic93/e2designer:latest
    BINTRAY_ZSYNC: bintray-zsync|technic|e2designer|e2designer
    BINTRAY_URL: https://api.bintray.com/content/technic/e2designer/e2designer

stages:
  - images
  - build
  - test
  - deploy

image-ubuntu:
  stage: images
  image: docker:git
  services:
    - docker:dind
  script:
    - cd docker
    - docker login -u $CI_DEPLOY_USER -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --pull -t $UBUNTU_IMAGE .
    - docker push $UBUNTU_IMAGE
  when: manual

format:
  stage: build
  before_script:
    - apt-get update && apt-get -y install clang-format git
  script:
    - clang-format -style=file -i
      $(find . -type d -path './Qt-Color-Widgets' -prune -iname '*.hpp' -o -iname '*.cpp')
    - git diff --exit-code
  allow_failure: true

before_script:
  # disable grep and exec part of the script
  - sed -i '/^TEST/d' /opt/qt511/bin/qt511-env.sh
  - . /opt/qt511/bin/qt511-env.sh
  - which qmake
  - qmake --version
  - g++ --version
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - ccache -sz

build:
  stage: build
  script:
    - mkdir -p build
    - pushd build
    - qmake .. "QMAKE_CXX = ccache g++"
    - make
    - ccache -s
    - make -C app INSTALL_ROOT=$(pwd)/appdir install
    - find appdir
    - curl -fsSL -o linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    - chmod a+x linuxdeployqt
    - curl -fsSL -o appimagetool https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
    - chmod a+x appimagetool
    - ./linuxdeployqt appdir/usr/share/applications/e2designer.desktop -bundle-non-qt-libs
    - ./appimagetool -u "$BINTRAY_ZSYNC|e2designer-_latestVersion-x86_64.AppImage.zsync" appdir
  artifacts:
    paths:
      - build/*.AppImage
      - build/*.AppImage.zsync
  cache:
    paths:
      - ccache/

test:
  stage: test
  script:
  - mkdir -p build && cd build
  - qmake .. "QMAKE_CXX = ccache g++"
  - make
  - make check
  cache:
    paths:
      - ccache/

deploy-AppImage:
  stage: deploy
  script:
    - export VERSION=$(git describe)
    - curl -T build/e2designer-x86_64.AppImage -u technic:$BINTRAY_API_KEY $BINTRAY_URL/$VERSION/e2designer-$VERSION-x86_64.AppImage
    - curl -T build/e2designer-x86_64.AppImage.zsync -u technic:$BINTRAY_API_KEY $BINTRAY_URL/$VERSION/e2designer-$VERSION-x86_64.AppImage.zsync
