image: rabits/qt:5.11-desktop

format:
  stage: build
  before_script:
    - sudo apt-get update && sudo apt-get -y install clang-format
  script:
    - clang-format -style=file -i
      $(find . -type d -path './Qt-Color-Widgets' -prune -iname '*.hpp' -o -iname '*.cpp')
    - git diff --exit-code

build:
  stage: build
  script:
    - mkdir build
    - pushd build
    - which qmake
    - qmake --version
    - g++ --version
    - qmake ..
    - make
    - make INSTALL_ROOT=appdir install
    - find appdir
    - curl -fsSL -o linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    - chmod a+x linuxdeployqt
    - export VERSION=$(git rev-parse --short HEAD)
    - ./linuxdeployqt appdir/usr/share/applications/e2designer.desktop -appimage
  artifacts:
    paths:
      - build/e2designer
  cache:
    paths:
      - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo "TODO"
