image: ubuntu:bionic

format:
  stage: build
  before_script:
    - sudo apt-get update && sudo apt-get -y install clang-format
  script:
    - clang-format -style=file -i
      $(find . -type d -path './Qt-Color-Widgets' -prune -iname '*.hpp' -o -iname '*.cpp')
    - git diff --exit-code

build:
  stage: build
  script:
    - apt-get update && apt-get -y install fuse curl make file g++ qt5-qmake qt5-default
    - mkdir build
    - pushd build
    - which qmake
    - qmake --version
    - g++ --version
    - qmake ..
    - make
    - make INSTALL_ROOT=appdir install
    - find appdir
    - export VERSION=$(git rev-parse --short HEAD)
    - curl -fsSL -o linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    - chmod a+x linuxdeployqt
    - ./linuxdeployqt --appimage-extract
    - ./squashfs-root/AppRun appdir/usr/share/applications/e2designer.desktop -appimage
  artifacts:
    paths:
      - build/*.AppImage
  cache:
    paths:
      - "build/*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo "TODO"
