image: rabits/qt:5.11-desktop

format:
  stage: build
  before_script:
    - sudo apt-get update && sudo apt-get -y install clang-format
  script:
    - clang-format -style=file -i
      $(find . -type d -path './Qt-Color-Widgets' -prune -iname '*.hpp' -o -iname '*.cpp')
    - git diff --exit-code

build:
  stage: build
  script:
    - mkdir build
    - pushd build
    - which qmake
    - qmake --version
    - g++ --version
    - qmake ..
    - make
  artifacts:
    paths:
      - build/e2designer
  cache:
    paths:
      - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo "TODO"
