image: rabits/qt:5.11-desktop

build:
  stage: build
  before_script:
    - apt-get update && apt-get -y install clang-format
  script:
    - mkdir build
    - pushd build
    - which qmake
    - qmake --version
    - g++ --version
    - qmake ..
    - make
  artifacts:
    paths:
      - build/e2designer
  cache:
    paths:
      - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo "TODO"
