image: ubuntu:bionic

format:
  stage: build
  before_script:
    - apt-get update && apt-get -y install clang-format git
  script:
    - clang-format -style=file -i
      $(find . -type d -path './Qt-Color-Widgets' -prune -iname '*.hpp' -o -iname '*.cpp')
    - git diff --exit-code

build:
  stage: build
  script:
    - apt-get update && apt-get -y install fuse curl make file g++ qt5-qmake qt5-default
    - mkdir -p build
    - pushd build
    - which qmake
    - qmake --version
    - g++ --version
    - qmake ..
    - make
    - make INSTALL_ROOT=appdir install
    - find appdir
    - curl -fsSL -o linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
    - chmod a+x linuxdeployqt
    - ./linuxdeployqt appdir/usr/share/applications/e2designer.desktop -appimage
  artifacts:
    paths:
      - build/*.AppImage
  cache:
    paths:
      - "build/*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo "TODO"

deploy-AppImage:
  stage: deploy
  script:
    - export VERSION=$(git describe)
    - curl -T e2designer-x86_64.AppImage -u technic:$BINTRAY_API_KEY https://api.bintray.com/content/technic/e2designer/e2designer/$VERSION/e2designer-$VERSION-x86_64.AppImage
