language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt593-trusty -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59base
  - source /opt/qt*/bin/qt*-env.sh

script:
  - mkdir build-qmake ; cd build-qmake # Check if it builds as a library using qmake.
  - qmake .. 
  - make -j$(nproc)
  - cd ..
  - mkdir build-cmake ; cd build-cmake # Check if it builds as a library using cmake.
  - cmake ..
  - make -j$(nproc)
  - cd ..
  - cd tests
  - bash start_test.sh # Run Tests
