name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Build
        run: |
          qmake
          make
      - name: Test
        run: |
          make check
      - name: Package
        run: |
          macdeployqt -verbose 2 -dmg app/e2designer.app
          find app
      - uses: actions/upload-artifact@v1
        with:
          name: macos installer
          path: app/e2designer.dmg
