name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_mac:
    runs-on: macos-latest

    env:
      BINTRAY_URL: https://api.bintray.com/content/technic/e2designer/e2designer
      BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Build
        run: |
          qmake
          make
      - name: Test
        run: |
          make check
      - name: Package
        run: |
          macdeployqt app/e2designer.app -verbose=2 -dmg 
          find app
      - uses: actions/upload-artifact@v1
        with:
          name: macos installer
          path: app/e2designer.dmg
      - name: Deploy to bintray
      - run: |
          export VERSION=$(git describe)
          curl -T app/e2designer.dmg -u "technic:$BINTRAY_API_KEY" "$BINTRAY_URL/$VERSION/e2designer-$VERSION.dmg"
